include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Style rules
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    prefer_final_fields: true
    prefer_final_in_for_each: true

    # Safety rules
    avoid_print: true
    avoid_relative_lib_imports: true

    avoid_slow_async_io: true
    avoid_type_to_string: true
    cancel_subscriptions: true
    close_sinks: true

    # Readability rules
    always_declare_return_types: true
    annotate_overrides: true
    avoid_unnecessary_containers: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true

    # Code quality
    avoid_empty_else: true
    avoid_unused_constructor_parameters: true
    no_duplicate_case_values: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_string_interpolations: true
    use_full_hex_values_for_flutter_colors: true
